'use client'

import DSDTopicPage from '@/components/DSDTopicPage'
import { FiFileText, FiMap } from 'react-icons/fi'

const content = {
    title: 'Virtual Memory',
    explanationSections: [
        {
            title: '📄 Concept of Virtual Memory',
            icon: <FiFileText className="w-6 h-6" />,
            content: `<span class="text-blue-400 font-semibold">Virtual Memory</span> gives the illusion of a memory larger than the actual physical RAM. It allows programs to be larger than physical memory.
      
      • <span class="text-cyan-300">Virtual Address:</span> Generated by the CPU.
      • <span class="text-cyan-300">Physical Address:</span> Actual address in RAM.
      • <span class="text-cyan-300">MMU (Memory Management Unit):</span> Translates virtual addresses to physical addresses.`,
        },
        {
            title: 'Paging and TLB',
            icon: <FiMap className="w-6 h-6" />,
            content: `<span class="text-lime-300 font-semibold">Paging:</span>
      • Memory is divided into fixed-size blocks called <span class="text-cyan-300">Pages</span> (virtual) and <span class="text-cyan-300">Frames</span> (physical).
      • A Page Table maps pages to frames.
      
      <span class="text-lime-300 font-semibold">TLB (Translation Lookaside Buffer):</span>
      • A small, fast cache inside the MMU that stores recent address translations to speed up paging.`,
            mermaid: `graph LR
    CPU[CPU] --Virtual Addr--> MMU
    subgraph MMU
    TLB[TLB]
    PT[Page Table Walker]
    end
    TLB --Hit--> PA[Physical Addr]
    TLB --Miss--> PT
    PT --> PA
    PA --> RAM[Main Memory]`,
        },
    ],
    practiceQuestions: [
        {
            question: 'What happens during a Page Fault?',
            solution: 'A Page Fault occurs when a requested page is not in the main memory (RAM).\n\nSteps:\n1. OS traps the fault.\n2. OS locates the page on the disk (swap space).\n3. OS loads the page into a free frame in RAM.\n4. Page Table is updated.\n5. Instruction is restarted.',
        },
    ],
}

export default function VirtualMemoryPage() {
    return <DSDTopicPage content={content} />
}
