'use client'

import DSDTopicPage from '@/components/DSDTopicPage'
import { FiSettings, FiCpu } from 'react-icons/fi'

const content = {
    title: 'Control Unit Design',
    explanationSections: [
        {
            title: '🎮 Control Unit Functions',
            icon: <FiSettings className="w-6 h-6" />,
            content: `The <span class="text-blue-400 font-semibold">Control Unit (CU)</span> is the brain of the CPU. It directs the flow of data and operation of the ALU and other components.
      
      <span class="text-amber-300 font-semibold">Functions:</span>
      • Fetches instructions from memory.
      • Decodes instructions.
      • Generates control signals to execute instructions.`,
        },
        {
            title: 'Hardwired vs Micro-programmed',
            icon: <FiCpu className="w-6 h-6" />,
            content: `There are two main approaches to designing the Control Unit:
      
      <span class="text-lime-300 font-semibold">1. Hardwired Control:</span>
      • Implemented using fixed logic circuits (gates, flip-flops, decoders).
      • <span class="text-cyan-300">Pros:</span> Very fast (RISC style).
      • <span class="text-cyan-300">Cons:</span> Complex design, difficult to modify.
      
      <span class="text-lime-300 font-semibold">2. Micro-programmed Control:</span>
      • Control signals are generated by a program (microcode) stored in Control Memory.
      • <span class="text-cyan-300">Pros:</span> Flexible, easy to modify (CISC style).
      • <span class="text-cyan-300">Cons:</span> Slower than hardwired.`,
            mermaid: `graph TD
    subgraph "Hardwired Control"
    IR[Instruction Register] --> Dec[Decoder]
    Step[Step Counter] --> Logic[Combinational Logic]
    Dec --> Logic
    Flags --> Logic
    Logic --> Signals[Control Signals]
    end
    
    subgraph "Micro-programmed Control"
    MIR[Instruction] --> Seq[Sequencer]
    Seq --> CM[Control Memory (ROM)]
    CM --> MBR[Micro-Instruction Reg]
    MBR --> Signals2[Control Signals]
    end`,
        },
    ],
    practiceQuestions: [
        {
            question: 'Which control unit design is faster and why?',
            solution: 'Hardwired Control is faster because it uses dedicated logic circuits to generate control signals directly, avoiding the memory access latency associated with fetching micro-instructions in Micro-programmed Control.',
        },
    ],
}

export default function ControlUnitDesignPage() {
    return <DSDTopicPage content={content} />
}
